sudo: required

language: go

go:
  - 1.14.1

services:
  - docker

cache:
  directories:
    - /root/go/pkg

env:
  global:
    - CGO_ENABLED=0
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64"

script:
  - GOBUILD=${GOBUILD} make -j build
  - ls -la build

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$TRAVIS_TAG" =~ ^v.*$ ]]; then make -j docker TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker TAG=latest COMMIT=$TRAVIS_COMMIT; fi

deploy:
  provider: releases
  api_key:
    secure: inCWsnZFjpCOk3SCEgOb/Ffr8gTR1ELprchGl3tvO9V21Zz9Lv8EVPVEbPxf8sjD7dZ48Jd+4+EcSOJRVcVfQac4ZId0hi1xpBFjcpQwVK1gXbQ4U4GY+1oGxdlRpKysUofiFdmFRZcty/eOHVahRzBEd2Ysp28y2QCI0xkp3YFuRXed876hmeUHUlmUjxhqjk9/dfHu8btAMVyI/A2SA7zetxt6QZ//PjP+qjjtlKRl/J2ZsClHbBJ7pV46x/8KRIIwsp45t5OcXd69OLBbEM2Hae7aLPfcSd4h5LmD0yKmXC+498TxtnLP1mw1V1BiFmAKf3nhuBiuSZNJeJ4XwqSzuRf/YXO3RA/U7H9kKn7t2va3a7i50CWObwI/K6Y4rpGpa74YgYRhuJBW5PNakhPGfst5iEQyjFwYmAACOgiwHqBcNH7gaUZoGzoJnlijHWm98v+8Qr4xRx96DNQomI08Y7qz1/n1LihEMHRHy+oxcjf6P4F7A3NQqbmNqo946A1xreKUW4NO918aJSM2Cc+1KNNlf8OjHbEFd3OHhqi7GkC4BBuBzkZ/5P12imVyR/MrT7xpD1uImz2wRtiiujhbWn20aOslDxRRiLxOMsqnXMP4Yf7IUa06y1L7xNwlCqHuaRordP9/MWQo1ZAnd4jj3x/UvtjCYWj9AMN6/gs=
  file:
    - build/nomad-firehose-linux-amd64
    - build/nomad-firehose-windows-amd64
    - build/nomad-firehose-darwin-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/nomad-firehose
